action_id: trunk-upgrade-available
date: 2023-05-28 14:23:03
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\n\x1b[0m"
  err: ""
timestamp: 1685283783
full_timestamp:
  nanos: 169595000
  seconds: 1685283783
trunk_version: 1.10.0
